<a href="https://colab.research.google.com/github/ghrahul/ML-DL-PRACTICE/blob/master/Time%20Series/prepraing_features_and_labels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [9]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print() 

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [10]:
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [11]:
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())

[4 5 6 7] [8]
[2 3 4 5] [6]
[5 6 7 8] [9]
[0 1 2 3] [4]
[1 2 3 4] [5]
[3 4 5 6] [7]


In [12]:
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print(f"X: {x.numpy()}")
  print(f"y: {y.numpy()}")

X: [[0 1 2 3]
 [2 3 4 5]]
y: [[4]
 [6]]
X: [[5 6 7 8]
 [4 5 6 7]]
y: [[9]
 [8]]
X: [[1 2 3 4]
 [3 4 5 6]]
y: [[5]
 [7]]
