<a href="https://colab.research.google.com/github/ghrahul/ML-DL-PRACTICE/blob/master/fast_ai_tabular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from fastai.tabular import * 

In [2]:
path = untar_data(URLs.ADULT_SAMPLE)

In [3]:
path

PosixPath('/root/.fastai/data/adult_sample')

In [5]:
df = pd.read_csv(path/'adult.csv')
df.head()

age          workclass  fnlwgt  ... hours-per-week  native-country salary
0   49            Private  101320  ...             40   United-States  >=50k
1   44            Private  236746  ...             45   United-States  >=50k
2   38            Private   96185  ...             32   United-States   <50k
3   38       Self-emp-inc  112847  ...             40   United-States  >=50k
4   42   Self-emp-not-inc   82297  ...             50   United-States   <50k

[5 rows x 15 columns]

In [0]:
procs = [FillMissing, Categorify, Normalize]


In [0]:
valid_idx = range(len(df)-2000, len(df))


In [0]:
dep_var = 'salary'
cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

In [10]:
data = TabularDataBunch.from_df(path, df, dep_var, valid_idx=valid_idx, procs=procs, cat_names=cat_names)
print(data.train_ds.cont_names)

['hours-per-week', 'capital-gain', 'fnlwgt', 'age', 'capital-loss', 'education-num']


In [11]:
(cat_x,cont_x),y = next(iter(data.train_dl))
for o in (cat_x, cont_x, y): print(to_np(o[:5])) # 3 2d numpy array

[[ 8  8  3  2  1  5  2 40  1]
 [ 5 10  3  4  1  5  2 40  1]
 [ 5  6  3  6  1  5  2 33  1]
 [ 5 12  3  4  1  5  2 40  1]
 [ 2 16  5  7  4  5  2 10  1]]
[[-0.035789 -0.145922  1.478922  0.100758 -0.216787  0.753904]
 [-0.035789  0.270844 -0.677195  0.173985 -0.216787  1.145728]
 [ 3.519043  0.383531  1.340953 -0.045696 -0.216787 -2.380691]
 [ 0.772127 -0.145922 -0.272397 -0.851194 -0.216787 -0.421569]
 [-1.651622 -0.145922  0.62646  -1.437011 -0.216787 -0.029745]]
[1 1 0 0 0]


In [12]:
learn = tabular_learner(data, layers=[200,100], emb_szs={'native-country': 10}, metrics=accuracy)
learn.fit_one_cycle(1, 1e-2)

In [13]:
learn.predict(df.iloc[0])

(Category >=50k, tensor(1), tensor([0.2352, 0.7648]))